experiment:
  name: "sklearn_regression_experiment"
  # tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  tracking_uri: http://127.0.0.1:5000
  artifact_location: "./metadata/mlflow/mlartifacts"

# Set the registry server URI. This property is especially useful if you have a registry
# server that’s different from the tracking server.
model_registry:
  # registry_uri: "sqlite:////tmp/registry.db"
  # FIXME::REQUIRED: Specifies the name of the Registered Model to use when registering a trained
  #                 model to the MLflow Model Registry.
  model_name: "taxi_fare_regressor"

# Override the default train / validation / test dataset split ratios
SPLIT_RATIOS: [0.80, 0.10, 0.10]

INGEST_CONFIG:
  location: "https://github.com/mlflow/recipes-examples/raw/refs/heads/main/regression/data/sample.parquet"
  using: parquet

INGEST_SCORING_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#batch-scoring
  location: "https://github.com/mlflow/recipes-examples/raw/refs/heads/main/regression/data/sample.parquet"
  using: parquet

PREDICT_OUTPUT_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#predict-step
  location: "./data/sample_output.parquet"
  using: parquet
