/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemId 
 * @param name 
 * @param price 
 */


data class Item (

    @Json(name = "item_id")
    val itemId: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "price")
    val price: kotlin.Double

) {


}

