components:
  schemas:
    Item:
      properties:
        item_id:
          format: int64
          title: Item Id
          type: integer
        name:
          title: Name
          type: string
        price:
          format: double
          title: Price
          type: number
      required:
      - item_id
      - name
      - price
      title: Item
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /item:
    get:
      operationId: get_item_item_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: Successful Response
      summary: Get Item
